package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
	"github.com/spf13/cobra/doc"

	cmd "github.com/inhandnet/devicemanager-cli/internal/cmd"
	apiCmd "github.com/inhandnet/devicemanager-cli/internal/cmd/api"
	authCmd "github.com/inhandnet/devicemanager-cli/internal/cmd/auth"
	configCmd "github.com/inhandnet/devicemanager-cli/internal/cmd/config"
	deviceCmd "github.com/inhandnet/devicemanager-cli/internal/cmd/device"
	devicegroupCmd "github.com/inhandnet/devicemanager-cli/internal/cmd/devicegroup"
	drcCmd "github.com/inhandnet/devicemanager-cli/internal/cmd/drc"
	edgeCmd "github.com/inhandnet/devicemanager-cli/internal/cmd/edge"
	firmwareCmd "github.com/inhandnet/devicemanager-cli/internal/cmd/firmware"
	systemCmd "github.com/inhandnet/devicemanager-cli/internal/cmd/system"
	taskCmd "github.com/inhandnet/devicemanager-cli/internal/cmd/task"
	tunnelCmd "github.com/inhandnet/devicemanager-cli/internal/cmd/tunnel"
	updateCmd "github.com/inhandnet/devicemanager-cli/internal/cmd/update"
	versionCmd "github.com/inhandnet/devicemanager-cli/internal/cmd/version"
	"github.com/inhandnet/devicemanager-cli/internal/factory"
)

func main() {
	f := factory.New()
	rootCmd := cmd.NewCmdRoot(f)
	rootCmd.AddCommand(authCmd.NewCmdAuth(f))
	rootCmd.AddCommand(configCmd.NewCmdConfig(f))
	rootCmd.AddCommand(apiCmd.NewCmdApi(f))
	rootCmd.AddCommand(deviceCmd.NewCmdDevice(f))
	rootCmd.AddCommand(devicegroupCmd.NewCmdDeviceGroup(f))
	rootCmd.AddCommand(tunnelCmd.NewCmdTunnel(f))
	rootCmd.AddCommand(drcCmd.NewCmdDRC(f))
	rootCmd.AddCommand(edgeCmd.NewCmdEdge(f))
	rootCmd.AddCommand(firmwareCmd.NewCmdFirmware(f))
	rootCmd.AddCommand(taskCmd.NewCmdTask(f))
	rootCmd.AddCommand(systemCmd.NewCmdSystem(f))
	rootCmd.AddCommand(updateCmd.NewCmdUpdate(f))
	rootCmd.AddCommand(versionCmd.NewCmdVersion(f))

	dir := "docs/commands"
	if len(os.Args) > 1 {
		dir = os.Args[1]
	}

	if err := os.MkdirAll(dir, 0o755); err != nil {
		fmt.Fprintf(os.Stderr, "Error creating directory: %v\n", err)
		os.Exit(1)
	}

	filePrepender := func(filename string) string { return "" }
	linkHandler := func(name string) string {
		return strings.TrimSuffix(name, ".md")
	}

	if err := doc.GenMarkdownTreeCustom(rootCmd, dir, filePrepender, linkHandler); err != nil {
		fmt.Fprintf(os.Stderr, "Error generating docs: %v\n", err)
		os.Exit(1)
	}

	// Rename files: replace spaces with underscores in filenames
	if err := filepath.Walk(dir, func(path string, info os.FileInfo, err error) error {
		if err != nil || info.IsDir() {
			return err
		}
		newName := strings.ReplaceAll(info.Name(), " ", "_")
		if newName != info.Name() {
			return os.Rename(path, filepath.Join(filepath.Dir(path), newName))
		}
		return nil
	}); err != nil {
		fmt.Fprintf(os.Stderr, "Error renaming files: %v\n", err)
		os.Exit(1)
	}

	count := 0
	_ = filepath.Walk(dir, func(path string, info os.FileInfo, err error) error {
		if err == nil && !info.IsDir() {
			count++
		}
		return nil
	})

	// Strip auto-generated footer lines from each file
	_ = filepath.Walk(dir, func(path string, info os.FileInfo, err error) error {
		if err != nil || info.IsDir() {
			return err
		}
		data, readErr := os.ReadFile(path)
		if readErr != nil {
			return nil
		}
		content := string(data)
		// Remove "###### Auto generated by spf13/cobra ..." lines
		lines := strings.Split(content, "\n")
		var cleaned []string
		for _, line := range lines {
			if strings.HasPrefix(line, "###### Auto generated") {
				continue
			}
			cleaned = append(cleaned, line)
		}
		result := strings.TrimRight(strings.Join(cleaned, "\n"), "\n") + "\n"
		_ = os.WriteFile(path, []byte(result), 0o644)
		return nil
	})

	// Also remove any SEE ALSO sections that reference parent commands
	_ = filepath.Walk(dir, func(path string, info os.FileInfo, err error) error {
		if err != nil || info.IsDir() {
			return err
		}
		data, readErr := os.ReadFile(path)
		if readErr != nil {
			return nil
		}
		content := string(data)
		if idx := strings.Index(content, "### SEE ALSO"); idx >= 0 {
			content = strings.TrimRight(content[:idx], "\n") + "\n"
			_ = os.WriteFile(path, []byte(content), 0o644)
		}
		return nil
	})

	disableAutoGenTag(rootCmd)

	fmt.Printf("Generated %d command docs in %s/\n", count, dir)
}

func disableAutoGenTag(cmd *cobra.Command) {
	cmd.DisableAutoGenTag = true
	for _, c := range cmd.Commands() {
		disableAutoGenTag(c)
	}
}
