package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
	"github.com/spf13/cobra/doc"

	rootCmd "github.com/inhandnet/devicemanager-cli/internal/cmd"
	apiCmd "github.com/inhandnet/devicemanager-cli/internal/cmd/api"
	authCmd "github.com/inhandnet/devicemanager-cli/internal/cmd/auth"
	configCmd "github.com/inhandnet/devicemanager-cli/internal/cmd/config"
	deviceCmd "github.com/inhandnet/devicemanager-cli/internal/cmd/device"
	devicegroupCmd "github.com/inhandnet/devicemanager-cli/internal/cmd/devicegroup"
	docsCmd "github.com/inhandnet/devicemanager-cli/internal/cmd/docs"
	drcCmd "github.com/inhandnet/devicemanager-cli/internal/cmd/drc"
	edgeCmd "github.com/inhandnet/devicemanager-cli/internal/cmd/edge"
	firmwareCmd "github.com/inhandnet/devicemanager-cli/internal/cmd/firmware"
	systemCmd "github.com/inhandnet/devicemanager-cli/internal/cmd/system"
	taskCmd "github.com/inhandnet/devicemanager-cli/internal/cmd/task"
	tunnelCmd "github.com/inhandnet/devicemanager-cli/internal/cmd/tunnel"
	updateCmd "github.com/inhandnet/devicemanager-cli/internal/cmd/update"
	versionCmd "github.com/inhandnet/devicemanager-cli/internal/cmd/version"
	"github.com/inhandnet/devicemanager-cli/internal/factory"
)

func main() {
	f := factory.New()
	root := rootCmd.NewCmdRoot(f)
	root.AddCommand(authCmd.NewCmdAuth(f))
	root.AddCommand(configCmd.NewCmdConfig(f))
	root.AddCommand(apiCmd.NewCmdApi(f))
	root.AddCommand(deviceCmd.NewCmdDevice(f))
	root.AddCommand(devicegroupCmd.NewCmdDeviceGroup(f))
	root.AddCommand(tunnelCmd.NewCmdTunnel(f))
	root.AddCommand(drcCmd.NewCmdDRC(f))
	root.AddCommand(edgeCmd.NewCmdEdge(f))
	root.AddCommand(firmwareCmd.NewCmdFirmware(f))
	root.AddCommand(taskCmd.NewCmdTask(f))
	root.AddCommand(systemCmd.NewCmdSystem(f))
	root.AddCommand(docsCmd.NewCmdDocs(f))
	root.AddCommand(updateCmd.NewCmdUpdate(f))
	root.AddCommand(versionCmd.NewCmdVersion(f))

	dir := "docs/commands"
	if len(os.Args) > 1 {
		dir = os.Args[1]
	}

	cleanDir := filepath.Clean(dir)

	if err := os.MkdirAll(cleanDir, 0o750); err != nil {
		fmt.Fprintf(os.Stderr, "Error creating directory: %v\n", err)
		os.Exit(1)
	}

	filePrepender := func(filename string) string { return "" }
	linkHandler := func(name string) string {
		return strings.TrimSuffix(name, ".md")
	}

	disableAutoGenTag(root)

	if err := doc.GenMarkdownTreeCustom(root, cleanDir, filePrepender, linkHandler); err != nil {
		fmt.Fprintf(os.Stderr, "Error generating docs: %v\n", err)
		os.Exit(1)
	}

	// Rename files: replace spaces with underscores in filenames
	renameFiles(cleanDir)

	// Count generated files
	count := 0
	_ = filepath.Walk(cleanDir, func(_ string, info os.FileInfo, err error) error {
		if err == nil && !info.IsDir() {
			count++
		}
		return nil
	})

	// Strip auto-generated footer and SEE ALSO sections
	cleanGeneratedFiles(cleanDir)

	fmt.Printf("Generated %d command docs in %s/\n", count, cleanDir)
}

func disableAutoGenTag(c *cobra.Command) {
	c.DisableAutoGenTag = true
	for _, sub := range c.Commands() {
		disableAutoGenTag(sub)
	}
}

func renameFiles(dir string) {
	_ = filepath.Walk(dir, func(path string, info os.FileInfo, err error) error {
		if err != nil || info.IsDir() {
			return err
		}
		newName := strings.ReplaceAll(info.Name(), " ", "_")
		if newName != info.Name() {
			return os.Rename(path, filepath.Join(filepath.Dir(path), newName))
		}
		return nil
	})
}

func cleanGeneratedFiles(dir string) {
	_ = filepath.Walk(dir, func(path string, info os.FileInfo, err error) error {
		if err != nil || info.IsDir() {
			return err
		}
		data, readErr := os.ReadFile(path)
		if readErr != nil {
			return nil
		}
		content := string(data)

		// Remove "###### Auto generated by spf13/cobra ..." lines
		lines := strings.Split(content, "\n")
		var cleaned []string
		for _, line := range lines {
			if strings.HasPrefix(line, "###### Auto generated") {
				continue
			}
			cleaned = append(cleaned, line)
		}
		content = strings.TrimRight(strings.Join(cleaned, "\n"), "\n") + "\n"

		// Remove SEE ALSO sections
		if idx := strings.Index(content, "### SEE ALSO"); idx >= 0 {
			content = strings.TrimRight(content[:idx], "\n") + "\n"
		}

		return os.WriteFile(path, []byte(content), 0o600)
	})
}
